// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Request struct {
	Name   string `json:"name"`
	Gender string `json:"gender,options=man|women"`
}

type Response struct {
	Message string `json:"message"`
	Data    any    `json:"data"`
}

type IdRequest struct {
	Id string `json:"name" path:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
