// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pbfile/product.proto

// 指定对应文件生成出来的pkg

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_pbfile_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbfile_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_pbfile_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductStock  int32                  `protobuf:"varint,1,opt,name=product_stock,json=productStock,proto3" json:"product_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_pbfile_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbfile_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_pbfile_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetProductStock() int32 {
	if x != nil {
		return x.ProductStock
	}
	return 0
}

var File_pbfile_product_proto protoreflect.FileDescriptor

const file_pbfile_product_proto_rawDesc = "" +
	"\n" +
	"\x14pbfile/product.proto\x12\aservice\"/\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\"6\n" +
	"\x0fProductResponse\x12#\n" +
	"\rproduct_stock\x18\x01 \x01(\x05R\fproductStock2V\n" +
	"\x0eProductService\x12D\n" +
	"\x0fGetProductStock\x12\x17.service.ProductRequest\x1a\x18.service.ProductResponseB\fZ\n" +
	"../serviceb\x06proto3"

var (
	file_pbfile_product_proto_rawDescOnce sync.Once
	file_pbfile_product_proto_rawDescData []byte
)

func file_pbfile_product_proto_rawDescGZIP() []byte {
	file_pbfile_product_proto_rawDescOnce.Do(func() {
		file_pbfile_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbfile_product_proto_rawDesc), len(file_pbfile_product_proto_rawDesc)))
	})
	return file_pbfile_product_proto_rawDescData
}

var file_pbfile_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbfile_product_proto_goTypes = []any{
	(*ProductRequest)(nil),  // 0: service.ProductRequest
	(*ProductResponse)(nil), // 1: service.ProductResponse
}
var file_pbfile_product_proto_depIdxs = []int32{
	0, // 0: service.ProductService.GetProductStock:input_type -> service.ProductRequest
	1, // 1: service.ProductService.GetProductStock:output_type -> service.ProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbfile_product_proto_init() }
func file_pbfile_product_proto_init() {
	if File_pbfile_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbfile_product_proto_rawDesc), len(file_pbfile_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbfile_product_proto_goTypes,
		DependencyIndexes: file_pbfile_product_proto_depIdxs,
		MessageInfos:      file_pbfile_product_proto_msgTypes,
	}.Build()
	File_pbfile_product_proto = out.File
	file_pbfile_product_proto_goTypes = nil
	file_pbfile_product_proto_depIdxs = nil
}
